version: '3'
services:
  # db:
  #   image: postgres
  #   # restart: always
  #   environment:
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: root
  #     POSTGRES_DB: patient_reg_system
  #   volumes:
  #     - postgres:/var/lib/postgresql/data
  #   # ports:
  #   #   - 5432:5432
  #   networks:
  #     - pern-app
  # pgadmin:
  #   image: dpage/pgadmin4
  #   # restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   ports:
  #     - 5050:80
  #   # volumes:
  #   #   - pgadmin:/var/lib/pgadmin
  #   depends_on:
  #     - db
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    ports:
      - 5000:5000
    volumes:
      - ./server:/app
      - /app/node_modules
    # depends_on:
    #   - db
    networks:
      - pern-app
  client:
    build: ./client
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    networks:
      - pern-app
networks:
  pern-app:
    driver: bridge
volumes:
  postgres:
    driver: local
  # pgadmin:
  #   driver: local